-- V24: interesados en exponer, capturados desde el formulario público "Quiero exponer"
-- de la SPA (sin autenticación). Es una tabla nueva y aislada: no toca puesto/inscripcion,
-- solo referencia a categoria para saber qué zona le interesa a cada persona.
--
-- No usa las columnas de auditoria con guion bajo (`_fecha_registro`, etc.) porque esas
-- asumen un usuario autenticado que registra/modifica (AuditoriaConfig), y aqui quien
-- escribe es siempre un visitante anonimo. Sigue en cambio el patron de `notificacion`
-- (V17): columnas propias, fecha_registro con default, sin FK a usuario.
--
-- Es idempotente.

CREATE TABLE IF NOT EXISTS public.interesado_stand (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo  varchar(200)  NOT NULL,
    celular          varchar(30)   NOT NULL,
    empresa          varchar(200)  NOT NULL,
    rubro            varchar(200)  NOT NULL,
    id_categoria     bigint        NOT NULL REFERENCES public.categoria(id),
    estado           varchar(20)   NOT NULL DEFAULT 'NUEVO',
    fecha_registro   timestamp     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interesado_stand_categoria ON public.interesado_stand(id_categoria);
CREATE INDEX IF NOT EXISTS idx_interesado_stand_fecha ON public.interesado_stand(fecha_registro DESC);
