spring.application.name=uniFex
server.port=7676
spring.datasource.url=jdbc:postgresql://virtual.uap.edu.bo:5432/v2_fexpo_uap
spring.datasource.username=postgres
spring.datasource.password=usic2024
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.thymeleaf.cache=false

app.upload-root=C:/uniFex/uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:/uniFex/tmp
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB


pasarela.url=https://pasarela.uap.edu.bo/v1/pago/nuevo
pasarela.key=AccessKey cd171945-e257-4bc5-a76b-cfa9ef1a9bc8

server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=X-Forwarded-Proto
server.tomcat.remoteip.remote-ip-header=X-Forwarded-For

