spring.application.name=uniFex
server.port=7676
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_uniFexpoUap
spring.datasource.username=postgres
spring.datasource.password=curso2021.
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.thymeleaf.cache=false

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

pasarela.url=https://pasarela.uap.edu.bo/v1/pago/nuevo
pasarela.key=AccessKey cd171945-e257-4bc5-a76b-cfa9ef1a9bc8